### ISSUE TITLE
Install Error at Manjaro (KDE)

### ISSUE THREAD

**Issue by xstable** [MycroftAI/mycroft-gui#127] opened 2023-03-10 09:27 UTC
**Describe the bug**
Package update fails with following error: 

```
CMake Error at CMakeLists.txt:46 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "6.4.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.15.8
    /lib/cmake/Qt5/Qt5Config.cmake, version: 5.15.8
```

**To Reproduce**
1. Install current Manjaro with KDE
2. Install mycroft-gui-git package
3. Read the error

**Expected behavior**
...mhh, I think it shouldn't throw an error  ;)

**Log files**
Also see the attached log file:   
[CMakeOutput.log](https://github.com/MycroftAI/mycroft-gui/files/10940509/CMakeOutput.log)

**Environment (please complete the following information):**
 - Device type: Desktop
 - OS: Manjaro

**Comment by AIIX** [comment] 2023-03-10 11:37
Please use the stable package release at https://github.com/MycroftAI/mycroft-gui/releases/tag/stable-qt5, Mycroft-GUI master branch has moved to QT6

Closing this issue since its not a bug. Distribution bugs should be filed with distributions directly

**Closed by AIIX** 2023-03-10 11:37 UTC
Labels: bug

**Comment by xstable** [comment] 2023-03-10 13:42
That don't work with the plasmoid applet. 
![image](https://user-images.githubusercontent.com/1778068/224331092-7113eb5f-ac20-4f48-bf72-e820845bc77a.png)

**Comment by AIIX** [comment] 2023-03-10 13:49
please install stable branches to install, if you are building stable QT5 branch then plasma5 applet should work

**Comment by xstable** [comment] 2023-03-12 17:05
@AIIX 
Ok, but I don't see what kind of stable branches you mean. 
If I do select "mycroft-gui" at pamc, it automatically select the one and only `plasma5-applets-mycroft-git`, and there are no other ones:

![image](https://user-images.githubusercontent.com/1778068/224560393-c8df57c0-d588-4568-8282-9d2ffda07588.png)

BTW: Can this issue stay open, till it's solved? Thx.

**Comment by AIIX** [comment] 2023-03-12 20:42
You are trying to build/install a QT6 mycroft gui against a QT5 environment, and that is not supported / possible. This is a packaging issue and not related to this repository

You can manually download the correct Qt5 version from here and install it using the dev setup script https://github.com/MycroftAI/mycroft-gui/releases/tag/stable-qt5

This is an issue that should have been opened up with your distribution or AUR package.
